=== LucasZamprogno/mutation-clustering-parallel/content/target/test/query.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Test Query",
    "description": "A test query and its expected response when passed to InsightFacade.performQuery",
    "type": "object",
    "properties": {
        "id": {
            "description": "A unique identifier for the test",
            "type": "string"
        },
        "title": {
            "description": "A meaningful test name that describes the query",
            "type": "string",
            "minLength": 5,
            "maxLength": 100
        },
        "description": {
            "description": "An extended test description",
            "type": "string"
        },
        "query": {
            "description": "The query that will be sent to performQuery"
        },
        "isQueryValid": {
            "description": "Flag indicated if the query is valid. For invalid queries, the result should be set to the error message returned by performQuery.",
            "type": "boolean"
        },
        "result": {
            "description": "The expected response from performQuery",
            "type": "array"
        }
    },
    "additionalProperties": false,
    "required": ["id", "title", "description", "query", "isQueryValid"]
}

=== LucasZamprogno/mutation-clustering-parallel/content/target/test/d1/queries/Indigo.json
{"id":"Indigo","title":"Handle double negation.","description":"Selects \"courses_dept\", \"courses_id\", and \"courses_avg\" and looks for all courses with not not 60% average, sorted by courses_dept","query":{"WHERE":{"NOT":{"NOT":{"EQ":{"courses_avg":60}}}},"OPTIONS":{"COLUMNS":["courses_dept","courses_id","courses_avg"],"ORDER":"courses_dept"}},"isQueryValid":true,"result":[{"courses_avg":60,"courses_id":"441","courses_dept":"busi"},{"courses_avg":60,"courses_id":"444","courses_dept":"busi"},{"courses_avg":60,"courses_id":"417","courses_dept":"chem"},{"courses_avg":60,"courses_id":"417","courses_dept":"chem"},{"courses_avg":60,"courses_id":"110","courses_dept":"dhyg"},{"courses_avg":60,"courses_id":"401","courses_dept":"dhyg"},{"courses_avg":60,"courses_id":"405","courses_dept":"dhyg"},{"courses_avg":60,"courses_id":"405","courses_dept":"dhyg"},{"courses_avg":60,"courses_id":"432","courses_dept":"hist"},{"courses_avg":60,"courses_id":"303","courses_dept":"phar"},{"courses_avg":60,"courses_id":"120","courses_dept":"phil"},{"courses_avg":60,"courses_id":"100","courses_dept":"test"}]}

=== LucasZamprogno/mutation-clustering-parallel/content/target/test/d1/queries/Mango.json
{"id":"Mango","title":"Contradictory query should be valid.","description":"This test looks for a course that is in department \"adhe\" and not in \"adhe\". This contradictory query should return 0 results without error.","query":{"WHERE":{"AND":[{"GT":{"courses_avg":90}},{"IS":{"courses_dept":"adhe"}},{"AND":[{"IS":{"courses_id":"550"}},{"NOT":{"IS":{"courses_dept":"adhe"}}}]}]},"OPTIONS":{"COLUMNS":["courses_dept","courses_id","courses_avg"],"ORDER":"courses_avg"}},"isQueryValid":true,"result":[]}

=== LucasZamprogno/mutation-clustering-parallel/content/target/test/d1/queries/Firefly.json
{"id":"Firefly","title":"Should be able to find all instructors in a dept with a partial name.","description":"Selects \"courses_dept\" and \"courses_instructor\", and looks for \"*a\" in \"courses_instructor\".","query":{"WHERE":{"AND":[{"IS":{"courses_instructor":"*a"}},{"IS":{"courses_dept":"cpsc"}}]},"OPTIONS":{"COLUMNS":["courses_dept","courses_instructor"]}},"isQueryValid":true,"result":[{"courses_dept":"cpsc","courses_instructor":"mcgrenere, joanna"},{"courses_dept":"cpsc","courses_instructor":"berg, celina"},{"courses_dept":"cpsc","courses_instructor":"berg, celina"},{"courses_dept":"cpsc","courses_instructor":"mcgrenere, joanna"},{"courses_dept":"cpsc","courses_instructor":"mcgrenere, joanna"},{"courses_dept":"cpsc","courses_instructor":"cooper, kendra"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"munzner, tamara"},{"courses_dept":"cpsc","courses_instructor":"munzner, tamara"},{"courses_dept":"cpsc","courses_instructor":"darwish, mohammad mostafa"},{"courses_dept":"cpsc","courses_instructor":"munzner, tamara"},{"courses_dept":"cpsc","courses_instructor":"cooper, kendra"},{"courses_dept":"cpsc","courses_instructor":"sheffer, alla"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"dunfield, joshua"},{"courses_dept":"cpsc","courses_instructor":"munzner, tamara"},{"courses_dept":"cpsc","courses_instructor":"sheffer, alla"},{"courses_dept":"cpsc","courses_instructor":"sheffer, alla"},{"courses_dept":"cpsc","courses_instructor":"munzner, tamara"},{"courses_dept":"cpsc","courses_instructor":"sheffer, alla"},{"courses_dept":"cpsc","courses_instructor":"munzner, tamara"},{"courses_dept":"cpsc","courses_instructor":"munzner, tamara"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"dawson, jessica"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"baniassad, elisa"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"dawson, jessica"},{"courses_dept":"cpsc","courses_instructor":"mcgrenere, joanna"},{"courses_dept":"cpsc","courses_instructor":"mcgrenere, joanna"},{"courses_dept":"cpsc","courses_instructor":"mcgrenere, joanna"},{"courses_dept":"cpsc","courses_instructor":"dawson, jessica"},{"courses_dept":"cpsc","courses_instructor":"mcgrenere, joanna"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"conati, cristina"},{"courses_dept":"cpsc","courses_instructor":"dawson, jessica"},{"courses_dept":"cpsc","courses_instructor":"mcgrenere, joanna"},{"courses_dept":"cpsc","courses_instructor":"munzner, tamara"},{"courses_dept":"cpsc","courses_instructor":"munzner, tamara"}]}

=== LucasZamprogno/mutation-clustering-parallel/content/target/test/d1/queries/Elixir.json
{"id":"Elixir","title":"Should be able to find sections with an or query on different keys.","description":"This test gets the \"courses_dept\",\"courses_id\", \"courses_fail\", \"courses_avg\" columns for cpsc courses with average = 88, or math sections with 20 < courses_fail < 30, sorted by courses_avg","query":{"WHERE":{"OR":[{"AND":[{"EQ":{"courses_avg":88}},{"IS":{"courses_dept":"cpsc"}}]},{"AND":[{"LT":{"courses_fail":30}},{"GT":{"courses_fail":20}},{"IS":{"courses_dept":"math"}}]}]},"OPTIONS":{"COLUMNS":["courses_dept","courses_id","courses_fail","courses_avg"],"ORDER":"courses_avg"}},"isQueryValid":true,"result":[{"courses_avg":53.12,"courses_id":"180","courses_dept":"math","courses_fail":21},{"courses_avg":53.12,"courses_id":"180","courses_dept":"math","courses_fail":21},{"courses_avg":55.26,"courses_id":"180","courses_dept":"math","courses_fail":26},{"courses_avg":55.3,"courses_id":"103","courses_dept":"math","courses_fail":27},{"courses_avg":55.74,"courses_id":"105","courses_dept":"math","courses_fail":21},{"courses_avg":55.74,"courses_id":"184","courses_dept":"math","courses_fail":26},{"courses_avg":56.77,"courses_id":"180","courses_dept":"math","courses_fail":28},{"courses_avg":56.83,"courses_id":"184","courses_dept":"math","courses_fail":22},{"courses_avg":56.83,"courses_id":"184","courses_dept":"math","courses_fail":22},{"courses_avg":57.37,"courses_id":"180","courses_dept":"math","courses_fail":22},{"courses_avg":57.56,"courses_id":"200","courses_dept":"math","courses_fail":22},{"courses_avg":58.04,"courses_id":"105","courses_dept":"math","courses_fail":23},{"courses_avg":58.42,"courses_id":"110","courses_dept":"math","courses_fail":22},{"courses_avg":58.52,"courses_id":"101","courses_dept":"math","courses_fail":24},{"courses_avg":58.9,"courses_id":"101","courses_dept":"math","courses_fail":24},{"courses_avg":58.9,"courses_id":"101","courses_dept":"math","courses_fail":24},{"courses_avg":58.96,"courses_id":"184","courses_dept":"math","courses_fail":22},{"courses_avg":59.32,"courses_id":"200","courses_dept":"math","courses_fail":23},{"courses_avg":59.37,"courses_id":"101","courses_dept":"math","courses_fail":23},{"courses_avg":59.74,"courses_id":"184","courses_dept":"math","courses_fail":24},{"courses_avg":60.17,"courses_id":"180","courses_dept":"math","courses_fail":22},{"courses_avg":60.5,"courses_id":"110","courses_dept":"math","courses_fail":25},{"courses_avg":60.58,"courses_id":"180","courses_dept":"math","courses_fail":29},{"courses_avg":60.9,"courses_id":"100","courses_dept":"math","courses_fail":21},{"courses_avg":61.35,"courses_id":"184","courses_dept":"math","courses_fail":22},{"courses_avg":61.58,"courses_id":"101","courses_dept":"math","courses_fail":21},{"courses_avg":61.75,"courses_id":"101","courses_dept":"math","courses_fail":21},{"courses_avg":61.75,"courses_id":"100","courses_dept":"math","courses_fail":21},{"courses_avg":62.03,"courses_id":"264","courses_dept":"math","courses_fail":29},{"courses_avg":62.17,"courses_id":"152","courses_dept":"math","courses_fail":23},{"courses_avg":62.29,"courses_id":"152","courses_dept":"math","courses_fail":22},{"courses_avg":62.38,"courses_id":"152","courses_dept":"math","courses_fail":22},{"courses_avg":62.4,"courses_id":"184","courses_dept":"math","courses_fail":22},{"courses_avg":62.59,"courses_id":"152","courses_dept":"math","courses_fail":21},{"courses_avg":62.82,"courses_id":"101","courses_dept":"math","courses_fail":21},{"courses_avg":62.89,"courses_id":"104","courses_dept":"math","courses_fail":23},{"courses_avg":62.99,"courses_id":"221","courses_dept":"math","courses_fail":28},{"courses_avg":63.1,"courses_id":"101","courses_dept":"math","courses_fail":23},{"courses_avg":63.12,"courses_id":"264","courses_dept":"math","courses_fail":28},{"courses_avg":63.16,"courses_id":"105","courses_dept":"math","courses_fail":23},{"courses_avg":63.33,"courses_id":"101","courses_dept":"math","courses_fail":22},{"courses_avg":63.36,"courses_id":"200","courses_dept":"math","courses_fail":22},{"courses_avg":63.42,"courses_id":"215","courses_dept":"math","courses_fail":24},{"courses_avg":63.88,"courses_id":"184","courses_dept":"math","courses_fail":26},{"courses_avg":63.89,"courses_id":"101","courses_dept":"math","courses_fail":25},{"courses_avg":63.89,"courses_id":"152","courses_dept":"math","courses_fail":29},{"courses_avg":64.06,"courses_id":"152","courses_dept":"math","courses_fail":21},{"courses_avg":64.09,"courses_id":"221","courses_dept":"math","courses_fail":26},{"courses_avg":64.23,"courses_id":"253","courses_dept":"math","courses_fail":22},{"courses_avg":64.26,"courses_id":"104","courses_dept":"math","courses_fail":23},{"courses_avg":64.3,"courses_id":"215","courses_dept":"math","courses_fail":26},{"courses_avg":64.34,"courses_id":"152","courses_dept":"math","courses_fail":21},{"courses_avg":64.35,"courses_id":"215","courses_dept":"math","courses_fail":22},{"courses_avg":64.53,"courses_id":"300","courses_dept":"math","courses_fail":28},{"courses_avg":64.64,"courses_id":"102","courses_dept":"math","courses_fail":22},{"courses_avg":64.72,"courses_id":"105","courses_dept":"math","courses_fail":27},{"courses_avg":64.76,"courses_id":"200","courses_dept":"math","courses_fail":29},{"courses_avg":64.91,"courses_id":"264","courses_dept":"math","courses_fail":23},{"courses_avg":65.04,"courses_id":"152","courses_dept":"math","courses_fail":27},{"courses_avg":65.21,"courses_id":"300","courses_dept":"math","courses_fail":25},{"courses_avg":65.39,"courses_id":"105","courses_dept":"math","courses_fail":21},{"courses_avg":65.44,"courses_id":"256","courses_dept":"math","courses_fail":21},{"courses_avg":65.52,"courses_id":"180","courses_dept":"math","courses_fail":21},{"courses_avg":65.6,"courses_id":"102","courses_dept":"math","courses_fail":28},{"courses_avg":65.63,"courses_id":"184","courses_dept":"math","courses_fail":24},{"courses_avg":65.71,"courses_id":"200","courses_dept":"math","courses_fail":22},{"courses_avg":65.74,"courses_id":"105","courses_dept":"math","courses_fail":22},{"courses_avg":65.74,"courses_id":"200","courses_dept":"math","courses_fail":21},{"courses_avg":65.99,"courses_id":"100","courses_dept":"math","courses_fail":22},{"courses_avg":66.2,"courses_id":"101","courses_dept":"math","courses_fail":21},{"courses_avg":66.26,"courses_id":"152","courses_dept":"math","courses_fail":24},{"courses_avg":66.32,"courses_id":"101","courses_dept":"math","courses_fail":21},{"courses_avg":66.41,"courses_id":"221","courses_dept":"math","courses_fail":21},{"courses_avg":66.87,"courses_id":"104","courses_dept":"math","courses_fail":23},{"courses_avg":67.03,"courses_id":"152","courses_dept":"math","courses_fail":28},{"courses_avg":67.11,"courses_id":"200","courses_dept":"math","courses_fail":23},{"courses_avg":67.36,"courses_id":"220","courses_dept":"math","courses_fail":23},{"courses_avg":67.53,"courses_id":"104","courses_dept":"math","courses_fail":24},{"courses_avg":67.71,"courses_id":"307","courses_dept":"math","courses_fail":23},{"courses_avg":67.73,"courses_id":"317","courses_dept":"math","courses_fail":21},{"courses_avg":67.77,"courses_id":"307","courses_dept":"math","courses_fail":21},{"courses_avg":67.79,"courses_id":"317","courses_dept":"math","courses_fail":21},{"courses_avg":67.88,"courses_id":"307","courses_dept":"math","courses_fail":23},{"courses_avg":68.02,"courses_id":"100","courses_dept":"math","courses_fail":22},{"courses_avg":68.03,"courses_id":"253","courses_dept":"math","courses_fail":22},{"courses_avg":68.45,"courses_id":"317","courses_dept":"math","courses_fail":21},{"courses_avg":68.73,"courses_id":"220","courses_dept":"math","courses_fail":21},{"courses_avg":68.84,"courses_id":"257","courses_dept":"math","courses_fail":22},{"courses_avg":69.3,"courses_id":"101","courses_dept":"math","courses_fail":24},{"courses_avg":69.53,"courses_id":"317","courses_dept":"math","courses_fail":23},{"courses_avg":69.64,"courses_id":"152","courses_dept":"math","courses_fail":21},{"courses_avg":69.65,"courses_id":"200","courses_dept":"math","courses_fail":21},{"courses_avg":69.94,"courses_id":"101","courses_dept":"math","courses_fail":23},{"courses_avg":70.08,"courses_id":"103","courses_dept":"math","courses_fail":27},{"courses_avg":70.34,"courses_id":"221","courses_dept":"math","courses_fail":26},{"courses_avg":70.42,"courses_id":"100","courses_dept":"math","courses_fail":24},{"courses_avg":70.6,"courses_id":"215","courses_dept":"math","courses_fail":25},{"courses_avg":70.67,"courses_id":"104","courses_dept":"math","courses_fail":24},{"courses_avg":71.27,"courses_id":"215","courses_dept":"math","courses_fail":23},{"courses_avg":74.75,"courses_id":"100","courses_dept":"math","courses_fail":23},{"courses_avg":88,"courses_id":"301","courses_dept":"cpsc","courses_fail":0},{"courses_avg":88,"courses_id":"544","courses_dept":"cpsc","courses_fail":0},{"courses_avg":88,"courses_id":"509","courses_dept":"cpsc","courses_fail":0},{"courses_avg":88,"courses_id":"509","courses_dept":"cpsc","courses_fail":0},{"courses_avg":88,"courses_id":"301","courses_dept":"cpsc","courses_fail":0},{"courses_avg":88,"courses_id":"544","courses_dept":"cpsc","courses_fail":0}]}

=== LucasZamprogno/mutation-clustering-parallel/content/target/test/d1/queries/Camelot.json
{"id":"Camelot","title":"Should be able to find course average for a course.","description":"This test gets the columns \"courses_dept\" , \"courses_id\", and \"courses_avg\" where \"courses_dept\" is \"cpsc\", \"courses_id\" is 310, sorted by \"courses_avg\"","query":{"WHERE":{"AND":[{"IS":{"courses_dept":"cpsc"}},{"IS":{"courses_id":"310"}}]},"OPTIONS":{"COLUMNS":["courses_dept","courses_id","courses_avg"],"ORDER":"courses_avg"}},"isQueryValid":true,"result":[{"courses_avg":72.27,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":73.16,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":74.45,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":74.99,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":75.14,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":75.4,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":75.54,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":75.57,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":75.72,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":75.8,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":75.97,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":76.31,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":76.52,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":77.11,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":77.13,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":77.63,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":77.78,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":77.8,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":78.22,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":78.32,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":78.68,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":78.68,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":78.69,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":79.04,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":79.12,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":79.12,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":79.5,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":80.24,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":80.32,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":80.34,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":80.34,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":80.35,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":81.17,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":81.17,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":81.18,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":81.88,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":81.88,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":84.6,"courses_id":"310","courses_dept":"cpsc"},{"courses_avg":84.6,"courses_id":"310","courses_dept":"cpsc"}]}
